// list_concepts — enumerate this origin's published knowledge concepts.
// The list is embedded at build time (content-addressed via tool_sha256).
var CONCEPTS = [{"id":"publishers/ccdd-gate.md","type":"Publisher","title":"ccdd-gate","description":"The CCDD gate tooling knowledge - how the deterministic verification gate works and integrates."},{"id":"publishers/ccdd.md","type":"Publisher","title":"CCDD (Complexity-Controlled Development)","description":"Specs, workflow and findings of the CCDD methodology - deterministic gates R1-R9 for AI-implemented code."},{"id":"publishers/game-protocol.md","type":"Publisher","title":"game-protocol","description":"An interaction protocol spec published in-source - its Pages serves the repo root, so the publisher lives inside the source tree."},{"id":"publishers/kdd.md","type":"Publisher","title":"KDD (Knowledge Driven Development)","description":"A real pre-existing OKF bundle with 40 concepts about the KDD methodology - contracts, validators, project templates. Also aggregated at the root origin under the kdd scope."},{"id":"publishers/llms-txt-skills.md","type":"Publisher","title":"llms-txt-skills (the standard itself)","description":"The spec publishes its own knowledge - 6 concepts covering the standard, adoption ladder, trust model, executable skills and consumption paths - plus a custom validator skill. Signed freshness attestations included."},{"id":"publishers/llmstxt-demo-site.md","type":"Publisher","title":"llmstxt-demo-site (Workers demo)","description":"The original demo publisher on Cloudflare Workers - executable skills including a POST write skill (create_payment against a real D1 stock), plus origin memory. Consumed by the reference gateway's CI."},{"id":"publishers/mauricioperera-github-io.md","type":"Publisher","title":"mauricioperera.github.io (root, multi-project)","description":"Root origin aggregating two projects on one llms.txt - the llms-txt-skills standard's own skills plus the KDD knowledge bundle under the kdd scope. Directly consumable."},{"id":"publishers/taskmd.md","type":"Publisher","title":"taskmd","description":"Task management as markdown - the taskmd format and workflow published as searchable knowledge."}];
registerTool({
  name: "list_concepts",
  description: "List all knowledge concepts published by this origin (id, type, title, description).",
  inputSchema: { type: "object", properties: {} },
  handler: function () { return { concepts: CONCEPTS }; }
});
